- README.md
**Changes**:
- changed url to URL
- corrected spelling mistakes
- corrected uppercase and apostrophe mistakes
- removed empty spaces at the end of lines.
> correction of some mistakes

- README.md
in README, adding the step `git add` for marking files as resolved
before continuing with rebase
> Adding the add step to rebasing

- README.md
Add some guidelines for commit messages, taken from https://chris.beams.io/posts/git-commit/#seven-rules.
> Add commit guidelines

- README.md
> Add JSON syntax highlight to README.md

- README.md
Just a few things I noticed while going through the guide. ❤️
> ✎ Improve general sentence structure and fix grammatical errors

- README.md
I didn't know what it was, so I added a Wikipedia link for anyone like me.
> Add Link to 'imperative mood' definition

- README.md
... and small fixes. ❤️
Let me know if you know of any other resources for this list. I have used Swagger before, but I am not aware of any other service, so if it comes to it, I can do some research on this topic. If just the 2 names on the list work just fine, merge this PR.
/cc @vpanjganj
> Remove Miredot and Enunciate from the list of API design tools

- README.md
> Remove duplicate block, move pure functions explanation

- README.md
fixes typo "distraction" to "distracting"
> fixes typo in refactoring code section.

- README.md
Despite the advice in the `README` it doesn't appear there's a `develop` branch here. 😝
> Adjust "a interactive" to "an interactive"

- README.md
Second command comes in handy especially when you pull branches for doing QA/CR but you don't merge/delete branches.
> Add commands for removing local branches

- README.md
Please review as I'm not sure whether all these changes are necessary. I may swap this commit with a revised one upon suggestions.
> Fix some periods in README

- README-zh.md
1. Localize more symbols like colon and period.
2. Improve some translation especially the section of Git.
3. Sync the doc with the English one.
4. Translate 'you' into Chinese using the honorific instead of the mixed usage.
> Fix Typo && Maybe Better Translation

- README-zh.md
1. Remove invalid whitespaces.
2. Fix some fatal translation.
3. Add some extra relevant words when translating(the Git part) to make it mostly like native Chinese speaking.
> Polish the translation

- README.md
- https://github.com/wearehive/project-guidelines/issues/74
- https://github.com/shieldfy/API-Security-Checklist
> Check the API Security Checklist Project

- README-ja.md
- README.md
Hi
I love this project and I wanted to translate it to Japanese.
That's why I created the version of Japanese.
If you wouldn't mind, please merge it.
> Add the README.md translated to Japanese

- README-ja.md
- README-ko.md
- README-zh.md
- README.md
Hi, I've just done the translation. I'll appreciate if you accept the PR. Thanks!
> Add Korean translation

- README-ja.md
Sorry. I just fixed some typo in the ja file. 
and add about the description of editorconfig 
Please check it
> Fix typo and add the description of editorconfig in ja-file

- README.md
The new sentence would read "If you don't have conflicts, skip this step."
> Fixes grammar of a sentence about rebasing

- README-zh.md
Fix typo and add space between Chinese and English.  
> 有研究显示，打字的时候不喜欢在中文和英文之间加空格的人，感情路都走得很辛苦，有七成的比例会在 34 岁的时候跟自己不爱的人结婚，而其余三成的人最后只能把遗产留给自己的猫。毕竟爱情跟书写都需要适时地留白。
> Studies have shown that when typing, people who do not like to have spaces between Chinese and English go very hard on the road of love. 70% of them will marry someone they do not love at the age of 34, and the remaining 30% Finally, only the legacy of their own cats left. After all, love and writing need to be promptly blank.
> Update Chinese version

- README-ko.md
removing the english "why" to add the korean "why"
> replacing english "why" with korean one

- README-pt-BR.md
Hello!
I've created this pull request because I've seen some issues with the Brazilian Portuguese translation. Hope you like it!
> Fixing issues pt/br translation

- README.sample.md
I think it looks better and saves space when the logo appears on the right.
> Align logo of README.sample.md to the right 🖼➡️
